In [1]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder

In [2]:
df = pd.read_csv('covid_toy.csv')

In [3]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

## Check for the unique values for each categorical column

In [5]:
df['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [6]:
df['cough'].unique()

array(['Mild', 'Strong'], dtype=object)

In [7]:
df['city'].unique()

array(['Kolkata', 'Delhi', 'Mumbai', 'Bangalore'], dtype=object)

In [8]:
df['has_covid'].unique()

array(['No', 'Yes'], dtype=object)

- As we can see from the dataset, 'gender' and 'city' are nominal so we will apply OneHotEncording.
- 'cough' is ordinal hence we will apply OrdinalEncorder.
- In the target column will apply LabelEncorder.

## Without ColumnTransformer

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1], test_size= 0.2, random_state= 10)

In [10]:
X_train

age  gender  fever   cough       city
90   59  Female   99.0  Strong      Delhi
70   68  Female  101.0  Strong      Delhi
50   19    Male  101.0    Mild      Delhi
44   20    Male  102.0  Strong      Delhi
76   80    Male  100.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
89   46    Male  103.0  Strong  Bangalore
28   16    Male  104.0    Mild    Kolkata
64   42    Male  104.0    Mild     Mumbai
15   70    Male  103.0  Strong    Kolkata
9    64  Female  101.0    Mild      Delhi

[80 rows x 5 columns]

In [11]:
# adding SimpleImputer to fever column
simp = SimpleImputer()
X_train_fvr = simp.fit_transform(X_train[['fever']])

# applying to test data
X_test_fvr = simp.transform(X_test[['fever']])

X_train_fvr

array([[ 99.        ],
       [101.        ],
       [101.        ],
       [102.        ],
       [100.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [103.        ],
       [ 99.        ],
       [101.        ],
       [100.65277778],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [ 98.        ],
       [ 99.        ],
       [ 99.        ],
       [100.65277778],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [100.65277778],
       [101.        ],
       [104.        ],
       [100.65277778],
       [104.        ],
       [ 98.        ],
       [ 98.        ],
       [100.65277778],
       [100

In [12]:
# using OrdinalEncorder to cough column

ord_enc = OrdinalEncoder(categories=[['Mild','Strong']])

X_train_cough = ord_enc.fit_transform(X_train[['cough']])

# applying to test data
X_test_cough = ord_enc.transform(X_test[['cough']])

X_train_cough

array([[1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],

In [13]:
# using OneHotEncorder to city and gender column
ohe = OneHotEncoder(sparse=False,drop='first')

X_train_city_gender = ohe.fit_transform(X_train[['city','gender']])

# applying to test data
X_test_city_gender = ohe.transform(X_test[['city','gender']])
X_train_city_gender

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 0.],


In [14]:
# Extracting Age column
X_train_age = X_train.drop(columns=['cough','fever','gender','city']).values

# applying to test data
X_test_age = X_test.drop(columns=['cough','fever','gender','city']).values
X_train_age

array([[59],
       [68],
       [19],
       [20],
       [80],
       [81],
       [73],
       [81],
       [14],
       [10],
       [27],
       [74],
       [69],
       [47],
       [82],
       [50],
       [72],
       [65],
       [84],
       [66],
       [34],
       [12],
       [17],
       [23],
       [18],
       [14],
       [40],
       [65],
       [65],
       [20],
       [47],
       [20],
       [ 5],
       [10],
       [13],
       [75],
       [51],
       [25],
       [71],
       [75],
       [80],
       [71],
       [38],
       [79],
       [64],
       [33],
       [ 5],
       [49],
       [83],
       [69],
       [25],
       [24],
       [15],
       [ 5],
       [23],
       [64],
       [73],
       [ 8],
       [16],
       [11],
       [44],
       [11],
       [83],
       [26],
       [56],
       [60],
       [65],
       [69],
       [38],
       [49],
       [60],
       [34],
       [19],
       [34],
       [27],
       [46],
       [16],

In [15]:
X_train_transformed = np.concatenate((X_train_age,X_train_fvr,X_train_city_gender,X_train_cough),axis =1)

In [16]:
X_test_transformed = np.concatenate((X_test_age,X_test_fvr,X_test_cough,X_test_city_gender),axis = 1)

In [17]:
X_test_transformed

array([[ 42.        , 100.65277778,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 51.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 22.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 55.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 51.        , 104.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 31.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 48.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 82.        , 100.65277778,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 49.        , 101.        ,   0.        ,   1.        ,
          0.    

## With ColumnTransformer 

In [18]:
from sklearn.compose import ColumnTransformer

In [19]:
col_trans = ColumnTransformer(transformers=[
    ('trns1',SimpleImputer(),['fever']),
    ('trns2', OneHotEncoder(drop='first', sparse=False),['gender','city']),
    ('trns3', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough'])
], remainder='passthrough')

In [20]:
X_train_transformed = col_trans.fit_transform(X_train)

In [21]:
X_train_transformed.shape

(80, 7)

In [22]:
X_test_transformed = col_trans.transform(X_test)

In [23]:
X_test_transformed

array([[100.65277778,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  42.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  51.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  22.        ],
       [100.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  55.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  51.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  31.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  48.        ],
       [100.65277778,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  82.        ],
       [101.        ,   0.        ,   1.        ,   0.        ,
          0.    